[working_directory]
wal_path = "C:\\rust\\projects\\rust-bdc\\wal.txt"
local_path = "C:\\rust\\projects\\rust-bdc"
file_system_type = "Replicated"

[network]
binding_address = "127.0.0.1"
orchestrator_port = "7777"
layout = {1={name="node-1",port="7778"}, 2={name="node-2",port="7779"}}

[cluster_settings]
execution_mode = "eager"